#!/bin/bash

#/ NAME
#/     build-perl -- build perl modules for irssi plugins
#/
#/ SYNOPSIS
#/     build perl

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_jason"

# entry point
function main {
  $shome/bin/build cpan $(cat $shome/Cpanfile)
}

require 'sub' "$BASH_SOURCE" "$@"
